"use client";
import 'bootstrap/dist/css/bootstrap.min.css';
import Container from 'react-bootstrap/Container';
import Navbar from '../components/Navbar' ;

export const metadata = {
  title: 'Lotificadora Gastos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body><Navbar/><Container>{children}</Container></body>
    </html>
  )
}
